import argparse
import os
import subprocess
import sys
from typing import List, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Reconstruct ODD/EVEN tilt series generated by generate_even_odd.py"
    )
    parser.add_argument(
        "input_dir",
        help="Directory containing ODD and EVEN subfolders with *.ali/*.tlt pairs",
    )
    parser.add_argument(
        "-z",
        "--vol_z",
        type=int,
        default=600,
        help="Output Z size passed to reconstruct.py (default: 600)",
    )
    parser.add_argument(
        "--method",
        default="wbp",
        choices=["wbp"],
        help="Reconstruction method for reconstruct.py (default: wbp)",
    )
    return parser.parse_args()


def find_pairs(folder: str) -> List[Tuple[str, str]]:
    pairs: List[Tuple[str, str]] = []
    if not os.path.isdir(folder):
        return pairs

    for entry in sorted(os.listdir(folder)):
        if not entry.lower().endswith(".ali"):
            continue
        base = os.path.splitext(entry)[0]
        ali_path = os.path.join(folder, entry)
        tlt_path = os.path.join(folder, f"{base}.tlt")
        if os.path.isfile(tlt_path):
            pairs.append((ali_path, tlt_path))
        else:
            print(f"Skipping {ali_path}: missing {tlt_path}")
    return pairs


def run_reconstruction(
    reconstruct_script: str, ali_path: str, tlt_path: str, vol_z: int, method: str
) -> None:
    base = os.path.splitext(os.path.basename(ali_path))[0]
    output_path = os.path.join(os.path.dirname(ali_path), f"{base}.mrc")
    cmd = [
        sys.executable,
        reconstruct_script,
        "-i",
        ali_path,
        "-o",
        output_path,
        "-t",
        tlt_path,
        "-z",
        str(vol_z),
        "--method",
        method,
    ]
    print(f"Reconstructing {ali_path} -> {output_path}")
    subprocess.run(cmd, check=True)


def main() -> None:
    args = parse_args()
    input_dir = os.path.abspath(args.input_dir)
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    reconstruct_script = os.path.join(project_root, "mrc", "reconstruct.py")

    if not os.path.isfile(reconstruct_script):
        raise FileNotFoundError(f"Cannot find reconstruct.py at {reconstruct_script}")

    subfolders = ["ODD", "EVEN"]
    any_processed = False
    for sub in subfolders:
        folder = os.path.join(input_dir, sub)
        pairs = find_pairs(folder)
        if not pairs:
            print(f"No pairs found in {folder}")
            continue
        for ali_path, tlt_path in pairs:
            run_reconstruction(
                reconstruct_script, ali_path, tlt_path, args.vol_z, args.method
            )
            any_processed = True

    if not any_processed:
        print("Nothing to reconstruct.")


if __name__ == "__main__":
    main()
